"""Add mood_history table

Revision ID: 58e31714cbfc
Revises: dfbaaa807602
Create Date: 2026-04-01 20:39:55.591469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e31714cbfc'
down_revision: Union[str, None] = 'dfbaaa807602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novelty_seeking', sa.Float(), nullable=False),
    sa.Column('social_bonding', sa.Float(), nullable=False),
    sa.Column('analytical_depth', sa.Float(), nullable=False),
    sa.Column('playfulness', sa.Float(), nullable=False),
    sa.Column('caution', sa.Float(), nullable=False),
    sa.Column('expressiveness', sa.Float(), nullable=False),
    sa.Column('source_emotion', sa.Text(), nullable=True),
    sa.Column('source_intensity', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mood_history')
    # ### end Alembic commands ###
