"""phase1 emotional episodes

Revision ID: 5b1b764bb98c
Revises: 929ac4e279a9
Create Date: 2026-03-30 18:55:32.931710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b1b764bb98c'
down_revision: Union[str, None] = '929ac4e279a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotional_episodes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trigger_event', sa.Text(), nullable=False),
    sa.Column('trigger_source', sa.Text(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('appraisal_goal_relevance', sa.Float(), nullable=False),
    sa.Column('appraisal_novelty', sa.Float(), nullable=False),
    sa.Column('appraisal_valence', sa.Float(), nullable=False),
    sa.Column('appraisal_agency', sa.Float(), nullable=False),
    sa.Column('appraisal_social_significance', sa.Float(), nullable=False),
    sa.Column('primary_emotion', sa.Text(), nullable=False),
    sa.Column('secondary_emotions', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('intensity', sa.Float(), nullable=False),
    sa.Column('decay_rate', sa.Float(), nullable=False),
    sa.Column('half_life_minutes', sa.Float(), nullable=False),
    sa.Column('delta_novelty_seeking', sa.Float(), server_default='0', nullable=False),
    sa.Column('delta_social_bonding', sa.Float(), server_default='0', nullable=False),
    sa.Column('delta_analytical_depth', sa.Float(), server_default='0', nullable=False),
    sa.Column('delta_playfulness', sa.Float(), server_default='0', nullable=False),
    sa.Column('delta_caution', sa.Float(), server_default='0', nullable=False),
    sa.Column('delta_expressiveness', sa.Float(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_formative', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('memory_encoded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_episodes_active', 'emotional_episodes', ['is_active'], unique=False, postgresql_where='is_active = true')
    op.create_index('idx_episodes_conversation', 'emotional_episodes', ['conversation_id'], unique=False)
    op.create_index('idx_episodes_created', 'emotional_episodes', ['created_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_episodes_formative', 'emotional_episodes', ['is_formative'], unique=False, postgresql_where='is_formative = true')
    # NOTE: idx_memories_embedding (HNSW) is not tracked by autogenerate — do NOT drop it
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_episodes_formative', table_name='emotional_episodes', postgresql_where='is_formative = true')
    op.drop_index('idx_episodes_created', table_name='emotional_episodes', postgresql_using='btree')
    op.drop_index('idx_episodes_conversation', table_name='emotional_episodes')
    op.drop_index('idx_episodes_active', table_name='emotional_episodes', postgresql_where='is_active = true')
    op.drop_table('emotional_episodes')
    # ### end Alembic commands ###
