"""phase0 tables

Revision ID: 929ac4e279a9
Revises: 
Create Date: 2026-03-29 23:57:25.679132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '929ac4e279a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_changes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.Text(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_config_changes_key', 'config_changes', ['config_key'], unique=False)
    op.create_index('idx_config_changes_time', 'config_changes', ['changed_at'], unique=False, postgresql_using='btree')
    op.create_table('consolidation_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.Text(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('episodes_replayed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('memories_promoted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('patterns_extracted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('links_created', sa.Integer(), server_default='0', nullable=False),
    sa.Column('memories_decayed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('memories_archived', sa.Integer(), server_default='0', nullable=False),
    sa.Column('personality_updated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('personality_drift_magnitude', sa.Float(), server_default='0', nullable=True),
    sa.Column('identity_check_triggered', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('identity_revised', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consolidation_time', 'consolidation_log', ['started_at'], unique=False, postgresql_using='btree')
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('mood_at_start', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mood_at_end', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_time', 'conversations', ['started_at'], unique=False, postgresql_using='btree')
    op.create_table('event_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('episode_id', sa.UUID(), nullable=True),
    sa.Column('memory_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('consolidation_id', sa.BigInteger(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_log_conversation', 'event_log', ['conversation_id'], unique=False)
    op.create_index('idx_event_log_time', 'event_log', ['recorded_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_event_log_type', 'event_log', ['event_type'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('memory_type', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1024), nullable=False),
    sa.Column('emotional_intensity', sa.Float(), nullable=True),
    sa.Column('primary_emotion', sa.Text(), nullable=True),
    sa.Column('valence', sa.Float(), nullable=True),
    sa.Column('source_episode_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('reinforcement_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('decay_rate', sa.Float(), server_default='0.0001', nullable=False),
    sa.Column('detail_retention', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('is_formative', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('decay_protection', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('is_labile', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('labile_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieval_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_retrieved', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consolidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memories_active', 'memories', ['is_archived'], unique=False, postgresql_where='is_archived = false')
    op.create_index('idx_memories_created', 'memories', ['created_at'], unique=False, postgresql_using='btree')
    op.create_index('idx_memories_formative', 'memories', ['is_formative'], unique=False, postgresql_where='is_formative = true')
    op.create_index('idx_memories_type', 'memories', ['memory_type'], unique=False)
    op.create_index('idx_memories_type_active', 'memories', ['memory_type', 'is_archived'], unique=False, postgresql_where='is_archived = false')
    # HNSW index for vector similarity search (cosine distance)
    op.execute("""
        CREATE INDEX idx_memories_embedding ON memories
        USING hnsw (embedding vector_cosine_ops)
        WITH (m = 16, ef_construction = 64)
    """)
    op.create_table('memory_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_memory_id', sa.UUID(), nullable=False),
    sa.Column('target_memory_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.Text(), nullable=False),
    sa.Column('strength', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('created_during', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_memory_id', 'target_memory_id', 'link_type', name='uq_memory_links_source_target_type')
    )
    op.create_index('idx_memory_links_source', 'memory_links', ['source_memory_id'], unique=False)
    op.create_index('idx_memory_links_target', 'memory_links', ['target_memory_id'], unique=False)
    op.create_table('temperament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novelty_seeking', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('social_bonding', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('analytical_depth', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('playfulness', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('caution', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('expressiveness', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('sensitivity', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('resilience', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('initialized_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Text(), server_default='1.0', nullable=False),
    sa.CheckConstraint('id = 1', name='ck_temperament_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temperament')
    op.drop_index('idx_memory_links_target', table_name='memory_links')
    op.drop_index('idx_memory_links_source', table_name='memory_links')
    op.drop_table('memory_links')
    op.drop_index('idx_memories_type_active', table_name='memories', postgresql_where='is_archived = false')
    op.drop_index('idx_memories_type', table_name='memories')
    op.drop_index('idx_memories_formative', table_name='memories', postgresql_where='is_formative = true')
    op.drop_index('idx_memories_created', table_name='memories', postgresql_using='btree')
    op.drop_index('idx_memories_active', table_name='memories', postgresql_where='is_archived = false')
    op.execute("DROP INDEX IF EXISTS idx_memories_embedding")
    op.drop_table('memories')
    op.drop_index('idx_event_log_type', table_name='event_log')
    op.drop_index('idx_event_log_time', table_name='event_log', postgresql_using='btree')
    op.drop_index('idx_event_log_conversation', table_name='event_log')
    op.drop_table('event_log')
    op.drop_index('idx_conversations_time', table_name='conversations', postgresql_using='btree')
    op.drop_table('conversations')
    op.drop_index('idx_consolidation_time', table_name='consolidation_log', postgresql_using='btree')
    op.drop_table('consolidation_log')
    op.drop_index('idx_config_changes_time', table_name='config_changes', postgresql_using='btree')
    op.drop_index('idx_config_changes_key', table_name='config_changes')
    op.drop_table('config_changes')
    # ### end Alembic commands ###
