"""Add embodied_state table

Revision ID: db76770ffb64
Revises: 58e31714cbfc
Create Date: 2026-04-03 22:15:06.202400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db76770ffb64'
down_revision: Union[str, None] = '58e31714cbfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embodied_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('cognitive_load', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('comfort', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_embodied_state_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    # Seed singleton row
    op.execute("INSERT INTO embodied_state (id, energy, cognitive_load, comfort) VALUES (1, 1.0, 0.0, 0.5)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embodied_state')
    # ### end Alembic commands ###
