"""Add mood_state table

Revision ID: dfbaaa807602
Revises: 5b1b764bb98c
Create Date: 2026-04-01 20:23:41.645411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfbaaa807602'
down_revision: Union[str, None] = '5b1b764bb98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novelty_seeking', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('social_bonding', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('analytical_depth', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('playfulness', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('caution', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('expressiveness', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_mood_state_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    # Seed the singleton row
    op.execute("INSERT INTO mood_state (id) VALUES (1)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mood_state')
    # ### end Alembic commands ###
